# Generated by Django 4.1 on 2024-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicleId", models.CharField(max_length=50)),
                ("vehicleName", models.CharField(max_length=50)),
                ("vehicleType", models.CharField(max_length=50)),
                ("purchaseDate", models.DateField(max_length=20)),
                ("buyerName", models.CharField(max_length=20)),
                ("tid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_VEHICLE",
            },
        ),
    ]
