# Generated by Django 4.1 on 2024-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="shoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("product", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("pid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_SHOPPINGCART",
            },
        ),
    ]
