# Generated by Django 4.1 on 2024-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_shoppingcart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("openDate", models.DateField(max_length=20)),
                ("version", models.CharField(max_length=20)),
                ("cid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_PROJECT",
            },
        ),
        migrations.DeleteModel(
            name="shoppingCart",
        ),
    ]
