# Generated by Django 4.1 on 2024-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_project_delete_shoppingcart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(max_length=20)),
                ("contactName", models.CharField(max_length=50)),
                ("mobile", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("sid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_Lead",
            },
        ),
    ]
