# Generated by Django 4.1 on 2024-08-13 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_lead"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="Date",
            new_name="date",
        ),
    ]
