# Generated by Django 4.1 on 2024-08-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0007_alter_lead_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("product", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=20)),
                ("amount", models.BigIntegerField(default=0)),
                ("oid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_ORDER",
            },
        ),
    ]
