# Generated by Django 4.1 on 2024-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0008_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("registrationDate", models.DateField(max_length=20)),
                ("paymentTerm", models.BigIntegerField(default=0)),
                ("sid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_SUPPLIER",
            },
        ),
    ]
