# Generated by Django 4.1 on 2024-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0009_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openDate", models.DateField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("assignTo", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("sid", models.IntegerField(default=0)),
                ("aid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "sos_issue",
            },
        ),
    ]
