# Generated by Django 4.1 on 2024-09-02 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0010_issue"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="issue",
            table="SOS_ISSUE",
        ),
    ]
