# Generated by Django 4.1 on 2024-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0012_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                ("pid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_WISHLIST",
            },
        ),
    ]
