# Generated by Django 4.1 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0013_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("mobile", models.BigIntegerField(default=0)),
                ("expertise", models.CharField(max_length=20)),
                ("did", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_DOCTOR",
            },
        ),
    ]
