# Generated by Django 4.1 on 2024-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0014_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=50)),
                ("userName", models.EmailField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("dob", models.DateField(max_length=20)),
                ("contactNumber", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_EMPLOYEE",
            },
        ),
    ]
