# Generated by Django 4.1 on 2024-09-06 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0015_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="contactNumber",
            new_name="number",
        ),
    ]
