# Generated by Django 4.1 on 2024-09-06 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0016_rename_contactnumber_employee_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="userName",
            new_name="username",
        ),
    ]
