# Generated by Django 4.1 on 2024-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0017_rename_username_employee_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initiativeName", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("startDate", models.DateField(max_length=20)),
                ("number", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_INITIATIVE",
            },
        ),
    ]
