# Generated by Django 4.1 on 2024-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0018_initiative"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="tid",
            field=models.IntegerField(default=0),
        ),
    ]
