# Generated by Django 4.1 on 2024-09-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0019_initiative_tid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=50)),
                ("creationDate", models.DateField(max_length=20)),
                ("assignedTo", models.CharField(max_length=50)),
                ("taskStatus", models.CharField(max_length=50)),
                ("tid", models.IntegerField(default=0)),
                ("aid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_TASK",
            },
        ),
    ]
