# Generated by Django 4.1 on 2024-09-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0024_staffmember_delete_issue_delete_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=50)),
                ("openingDate", models.DateField(max_length=20)),
                ("requiredExperience", models.CharField(max_length=50)),
                ("condition", models.CharField(max_length=50)),
                ("cid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_POSITION",
            },
        ),
    ]
