# Generated by Django 4.1 on 2024-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0025_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=50)),
                ("illness", models.CharField(max_length=50)),
                ("prescriptionDate", models.DateField(max_length=20)),
                ("dosage", models.BigIntegerField(default=0)),
                ("mid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_MEDICATION",
            },
        ),
    ]
