# Generated by Django 4.1 on 2024-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0030_portfoliomanagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientName", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("contactNumber", models.BigIntegerField(default=0)),
                ("importance", models.CharField(max_length=250)),
                ("cid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_CUSTOMER",
            },
        ),
    ]
