# Generated by Django 4.1 on 2024-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0031_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.BigIntegerField(default=0)),
                ("purchasePrice", models.FloatField(default=0)),
                ("purchaseDate", models.DateField(max_length=20)),
                ("orderType", models.CharField(max_length=50)),
                ("oid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "SOS_MARKET",
            },
        ),
    ]
